### ISSUE TITLE
Dimensions swapped in Lesson 2a

### ISSUE THREAD

**Issue by aazuspan** [developmentseed/tensorflow-eo-training#11]
There's [a small error in Lesson 2a](https://github.com/developmentseed/tensorflow-eo-training/blob/bf38916e06ef91c5ab73c9465ba2c7c7cc772300/ds_book/docs/Lesson2a_get_planet_NICFI.ipynb?short_path=e24023a#L714).

```python
rgb = rgb.transpose(2, 1, 0)
```

This inadvertently swaps the x and y dimensions of the image when it should just swap the channel dimension to the first axis. You can compare the shape of `rgb` with `mosaic` to confirm.

```python
>>> mosaic.shape
(5, 8192, 4096)

>>> rgb.shape
(3, 4096, 8192)
```

The code below works as expected.

```python
rgb = rgb.transpose(2, 0, 1)
```

```python
>>> mosaic.shape
(5, 8192, 4096)

>>> rgb.shape
(3, 8192, 4096)
```

Thanks for the great tutorial series!

**Comment by lillythomas** [comment]
Thank you so much for catching this and providing great documentation of the error @aazuspan it's been fixed by PR #13.
